apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord-team
    receivers:
      - uid: discord-team-webhook
        type: discord
        settings:
          url: $__env{DISCORD_WEBHOOK_URL}
          use_discord_username: false
        disableResolveMessage: false
